export const VIEWER_COPY = {
  en: {
    heroEyebrow: "Operational command",
    heroTitle: "Operations Home",
    heroSubtitle:
      "A precise command interface for device readiness, inspection coverage, and field location awareness with a calm military-grade layout.",
    heroUser: "Signed in as",
    heroRole: "Monitoring access only",
    latestSync: "Latest inspection",
    quickCoverage: "Coverage",
    totalDevices: "Total Devices",
    totalDevicesHint: "All registered units currently inside command visibility.",
    healthyDevices: "Healthy Devices",
    healthyDevicesHint: "Units currently reporting stable operational readiness.",
    attentionDevices: "Need Attention",
    attentionDevicesHint: "Devices that require review, maintenance, or follow-up.",
    totalInspections: "Inspections Logged",
    noInspectionYet: "No inspections logged yet.",
    latestInspections: "Latest Inspections",
    latestInspectionsHint: "Most recent checks across visible devices.",
    attentionList: "Priority Queue",
    attentionListHint: "Devices that should be watched first.",
    noAttentionDevices: "All monitored devices are currently healthy.",
    search: "Search by code, name, serial, building, or zone",
    status: "Status",
    allClusters: "All clusters",
    allBuildings: "All buildings",
    allZones: "All zones",
    allDirections: "All directions",
    clearFilters: "Reset filters",
    devicesTable: "Devices Command Board",
    devicesTableHint: "Health, location, and latest inspection in one place.",
    inspectionsTable: "Inspection Log Board",
    inspectionsTableHint: "Recent inspection records filtered by your current operational view.",
    analyticsTitle: "Operational Analytics",
    analyticsHint: "Quick health ratios and location ranking for command review.",
    noDeviceRows: "No devices match the current filters.",
    noInspectionRows: "No inspections match the current filters.",
    noLocationsRows: "No locations are available for the current filters.",
    locationHint: "Tap to filter devices in this site.",
    device: "Device",
    location: "Location",
    lastInspection: "Last Inspection",
    inspectionsCount: "Inspections",
    notes: "Notes",
    noNotes: "No notes",
    unknown: "Unknown",
    devicesShort: "Devices",
    inspectionsShort: "Checks",
    lastCheckShort: "Last Check",
    performanceBoard: "Command Board",
    performanceHint: "A compact summary of operational readiness and inspection reach.",
    deviceMix: "Device Readiness Mix",
    topLocations: "Priority Locations",
    latestPulse: "Latest Activity Feed",
    healthyRate: "Healthy Rate",
    attentionRate: "Attention Rate",
    inspectionReach: "Inspection Reach",
    activeFilters: "Active Filters",
    noFilter: "No active filter",
    readinessOverview: "Readiness Overview",
    strategicLayout: "Strategic Layout",
    homeTab: "Home",
    devicesTab: "Devices",
    inspectionsTab: "Inspections",
    locationsTab: "Locations",
    analyticsTab: "Analytics",
  },
  ar: {
    heroEyebrow: "قيادة تشغيلية",
    heroTitle: "الرئيسية",
    heroSubtitle:
      "واجهة قيادة دقيقة لمتابعة جاهزية الأجهزة وتغطية الفحوصات وتموضع المواقع بتصميم هادئ ومنظم وقوي.",
    heroUser: "تسجيل الدخول باسم",
    heroRole: "وصول متابعة فقط",
    latestSync: "آخر فحص",
    quickCoverage: "التغطية",
    totalDevices: "إجمالي الأجهزة",
    totalDevicesHint: "كل الأجهزة المتاحة حالياً داخل نطاق الرؤية التشغيلية.",
    healthyDevices: "أجهزة سليمة",
    healthyDevicesHint: "وحدات تعمل حالياً بجاهزية تشغيل مستقرة.",
    attentionDevices: "تحتاج متابعة",
    attentionDevicesHint: "أجهزة تحتاج مراجعة أو صيانة أو متابعة قريبة.",
    totalInspections: "إجمالي الفحوصات",
    noInspectionYet: "لا توجد فحوصات مسجلة حتى الآن.",
    latestInspections: "أحدث الفحوصات",
    latestInspectionsHint: "أحدث عمليات الفحص على الأجهزة الظاهرة للمستخدم.",
    attentionList: "قائمة الأولوية",
    attentionListHint: "الأجهزة التي تحتاج مراقبة أولاً.",
    noAttentionDevices: "كل الأجهزة الحالية بحالة جيدة.",
    search: "ابحث بالكود أو الاسم أو السيريال أو المبنى أو المنطقة",
    status: "الحالة",
    allClusters: "كل المجموعات",
    allBuildings: "كل المباني",
    allZones: "كل المناطق",
    allDirections: "كل الاتجاهات",
    clearFilters: "إعادة ضبط الفلاتر",
    devicesTable: "لوحة الأجهزة",
    devicesTableHint: "حالة الجهاز والموقع وآخر فحص في مكان واحد.",
    inspectionsTable: "سجل الفحوصات",
    inspectionsTableHint: "سجلات الفحص المعروضة حسب الفلاتر الحالية.",
    analyticsTitle: "التحليلات التشغيلية",
    analyticsHint: "ملخص سريع للنسب التشغيلية وترتيب المواقع للمراجعة.",
    noDeviceRows: "لا توجد أجهزة تطابق الفلاتر الحالية.",
    noInspectionRows: "لا توجد فحوصات تطابق الفلاتر الحالية.",
    noLocationsRows: "لا توجد مواقع متاحة بالفلاتر الحالية.",
    locationHint: "اضغط لتطبيق فلتر هذا الموقع.",
    device: "الجهاز",
    location: "الموقع",
    lastInspection: "آخر فحص",
    inspectionsCount: "عدد الفحوصات",
    notes: "ملاحظات",
    noNotes: "لا توجد ملاحظات",
    unknown: "غير معروف",
    devicesShort: "أجهزة",
    inspectionsShort: "فحوصات",
    lastCheckShort: "آخر تفتيش",
    performanceBoard: "لوحة القيادة",
    performanceHint: "ملخص عملي سريع لحالة الجاهزية ونطاق الفحص.",
    deviceMix: "توزيع جاهزية الأجهزة",
    topLocations: "المواقع ذات الأولوية",
    latestPulse: "آخر النشاطات",
    healthyRate: "نسبة السليم",
    attentionRate: "نسبة المتابعة",
    inspectionReach: "نطاق الفحص",
    activeFilters: "الفلاتر النشطة",
    noFilter: "لا توجد فلاتر مفعلة",
    readinessOverview: "نظرة الجاهزية",
    strategicLayout: "المخطط الاستراتيجي",
    homeTab: "الرئيسية",
    devicesTab: "الأجهزة",
    inspectionsTab: "الفحوصات",
    locationsTab: "المواقع",
    analyticsTab: "التحليلات",
  },
};
