
import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    dir: "ltr",
    brand: "SmartIT Inspect",
    brandSub: "SmartIT Inspection",
    home: "Home",
    tasks: "Tasks",
    technicians: "Technicians",
    devices: "Devices",
    inspections: "Inspections",
    analytics: "Analytics",
    locations: "Locations",
    refresh: "Refresh Data",
    loading: "Loading...",
    overview: "Dashboard Overview",
    techniciansStat: "Technicians",
    activeStaff: "Active staff",
    completed: "Completed",
    tasksDone: "Tasks done",
    pending: "Pending",
    inQueue: "In queue",
    emergency: "Emergency",
    urgent: "Urgent",
    devicesLabel: "Devices",
    total: "Total",
    maintenance: "Maintenance",
    due: "Due",
    taskStatus: "Task Status",
    weeklyTrend: "Weekly Trend",
    progressTracking: "Progress tracking",
    taskDistribution: "Task Distribution",
    monthlyInspections: "Monthly Inspections",
    viewAll: "View All",
    title: "Title",
    technician: "Technician",
    status: "Status",
    time: "Time",
    image: "Image",
    noTaskData: "No task data yet",
    noTrendData: "No trend data",
    noMonthlyInspections: "No monthly inspections yet",
    noDevices: "No devices available",
    code: "Code",
    deviceName: "Device Name",
    barcode: "Barcode",
    serialNumber: "Serial Number",
    currentStatus: "Current Status",
    lastInspection: "Last Inspection",
    action: "Action",
    history: "History",
    deviceHistory: "Device Status History",
    noHistory: "No status history for this device yet.",
    createTask: "Create Task",
    technicianField: "Technician",
    device: "Device",
    createdBy: "Created By (Admin ID)",
    scheduledDate: "Scheduled Date",
    frequency: "Frequency",
    emergencyTask: "Emergency Task",
    notes: "Notes",
    allStatuses: "All statuses",
    emergencyOnly: "Emergency only",
    search: "Search...",
    taskId: "ID",
    location: "Location",
    schedule: "Schedule",
    deleteTask: "Delete",
    noTasksFilter: "No tasks match the current filter.",
    addTechnician: "Add New Technician",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    username: "Username",
    officeNumber: "Office Number / ID",
    phone: "Phone",
    jobTitle: "Job Title",
    region: "Region",
    password: "Password",
    saveTechnician: "Save Technician",
    techActivity: "Technician Activity",
    name: "Name",
    assigned: "Assigned",
    completedTasks: "Completed",
    inspectionsCount: "Inspections",
    lastActivity: "Last Activity",
    recentActivity: "Recent Activity",
    noActivity: "No activity yet.",
    allTechnicians: "All technicians",
    allLocations: "All locations",
    currentMonthOnly: "Current month only",
    noInspections: "No inspections match current filters.",
    selectTech: "Select technician",
    selectDevice: "Select device",
    totalTechnicians: "Total Technicians",
    active: "Active",
    totalTasks: "Total Tasks",
    exampleId: "Example: 1",
    anyNotes: "Any additional notes",
    techSaved: "Technician saved successfully.",
    failedSave: "Failed to save technician.",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yes: "Yes",
    no: "No",
    week: "Week",
    noLocations: "No locations found.",
    building: "Building",
    cluster: "Cluster",
    troubleshooting: "Troubleshooting"
  },
  ar: {
    dir: "rtl",
    brand: "سمارت IT",
    brandSub: "تفتيش سمارت IT",
    home: "الرئيسية",
    tasks: "المهام",
    technicians: "الفنيون",
    devices: "الأجهزة",
    inspections: "الفحوصات",
    analytics: "التحليلات",
    locations: "المواقع",
    refresh: "تحديث البيانات",
    loading: "جارٍ التحميل...",
    overview: "نظرة عامة على اللوحة",
    techniciansStat: "الفنيون",
    activeStaff: "موظف نشط",
    completed: "مكتملة",
    tasksDone: "مهام منجزة",
    pending: "معلقة",
    inQueue: "في الانتظار",
    emergency: "طوارئ",
    urgent: "عاجل",
    devicesLabel: "الأجهزة",
    total: "الإجمالي",
    maintenance: "الصيانة",
    due: "مستحقة",
    taskStatus: "حالة المهام",
    weeklyTrend: "الاتجاه الأسبوعي",
    progressTracking: "تتبع التقدم",
    taskDistribution: "توزيع المهام",
    monthlyInspections: "فحوصات الشهر",
    viewAll: "عرض الكل",
    title: "العنوان",
    technician: "الفني",
    status: "الحالة",
    time: "الوقت",
    image: "صورة",
    noTaskData: "لا توجد مهام بعد",
    noTrendData: "لا توجد بيانات اتجاه",
    noMonthlyInspections: "لا توجد فحوصات شهرية بعد",
    noDevices: "لا توجد أجهزة متاحة",
    code: "الكود",
    deviceName: "اسم الجهاز",
    barcode: "الباركود",
    serialNumber: "الرقم التسلسلي",
    currentStatus: "الحالة الحالية",
    lastInspection: "آخر فحص",
    action: "إجراء",
    history: "السجل",
    deviceHistory: "سجل حالة الجهاز",
    noHistory: "لا يوجد سجل لهذا الجهاز بعد.",
    createTask: "إنشاء مهمة",
    technicianField: "الفني",
    device: "الجهاز",
    createdBy: "أنشئت بواسطة (ID المشرف)",
    scheduledDate: "تاريخ الجدولة",
    frequency: "التكرار",
    emergencyTask: "مهمة طارئة",
    notes: "ملاحظات",
    allStatuses: "كل الحالات",
    emergencyOnly: "الطوارئ فقط",
    search: "بحث...",
    taskId: "الرقم",
    location: "الموقع",
    schedule: "الجدول",
    deleteTask: "حذف",
    noTasksFilter: "لا توجد مهام تطابق الفلتر الحالي.",
    addTechnician: "إضافة فني جديد",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    email: "البريد الإلكتروني",
    username: "اسم المستخدم",
    officeNumber: "رقم المكتب / الهوية",
    phone: "الهاتف",
    jobTitle: "المسمى الوظيفي",
    region: "المنطقة",
    password: "كلمة المرور",
    saveTechnician: "حفظ الفني",
    techActivity: "نشاط الفنيين",
    name: "الاسم",
    assigned: "المُسند",
    completedTasks: "المكتملة",
    inspectionsCount: "الفحوصات",
    lastActivity: "آخر نشاط",
    recentActivity: "النشاط الأخير",
    noActivity: "لا يوجد نشاط بعد.",
    allTechnicians: "كل الفنيين",
    allLocations: "كل المواقع",
    currentMonthOnly: "الشهر الحالي فقط",
    noInspections: "لا توجد فحوصات تطابق الفلاتر الحالية.",
    selectTech: "اختر فنياً",
    selectDevice: "اختر جهازاً",
    totalTechnicians: "إجمالي الفنيين",
    active: "نشط",
    totalTasks: "إجمالي المهام",
    exampleId: "مثال: 1",
    anyNotes: "أي ملاحظات إضافية",
    techSaved: "تم حفظ الفني بنجاح.",
    failedSave: "فشل حفظ الفني.",
    daily: "يومي",
    weekly: "أسبوعي",
    monthly: "شهري",
    yes: "نعم",
    no: "لا",
    week: "الأسبوع",
    noLocations: "لا توجد مواقع.",
    building: "المبنى",
    cluster: "المجموعة",
    troubleshooting: "إدارة الأعطال"
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ar");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.dir = translations[lang].dir;
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang];
  const toggleLang = () => setLang((l) => (l === "ar" ? "en" : "ar"));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
